spring.application.name=gestor-tareas-api
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=una-clave-secreta-muy-larga-que-nadie-debe-conocer-cambiar-en-produccion-123456789
jwt.expiration=86400000